### getting main route
GET http://localhost:4000/


# API endpoints
### getting news headlines
GET http://localhost:4000/news/top-headlines


### getting tech news
GET http://localhost:4000/news/technology


### getting science news
GET http://localhost:4000/news/science


### Posting or adding a product
POST http://localhost:4000/news/search
Content-Type: application/json

{
  "search": "chelsea",
}